### ISSUE TITLE
Focus popup windows

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#101]
For example in file transfer / create directory, the focus should be right inside the popup window's text entry...

There are probably other instances of similar UI bugs...

**Comment by axlbonnet** [comment]
Indeed, it is currently necessary to click on the input field before entering text.

**Comment by axlbonnet** [comment]
Correct the "create directory" focus and quickly look if there are similar situations elsewhere.
