### ISSUE TITLE
Explain acronyms

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#109]
The use of acronyms may be good for page density, but at least explain them.

Examples:
- Doi on "Publications" tab
- LFN on "Applications" tab (also have a look at "Cardiac images" tab)
- SURL on "Zombie files" tab
- LFC files on "SSH connections" tab

There may be other ones...

**Comment by axlbonnet** [comment]
I think "DOI" is well known for all our researchers users.
The others are for admin use and are well known by all admins.
