### ISSUE TITLE
Contact UI should change after message has been sent

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#112]
when using the "experiencing problem" button, a "Contact" tab opens where you can send a message to the admin team.

After clicking the "Submit" button, the UI stays the same (appart from the popup that "Contact successfully sent").

What should happen: at least reset the form, or get back to where the user was before clicking the "experiencing problem" button.

**Comment by axlbonnet** [comment]
Indeed, users reports are sometime received twice.
