### ISSUE TITLE
Discrepancies in user/group creation process

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#114]
When creating a new user, if there is a problem creating the home directory, the account is created regardless (and an admin can manually create the home dir afterwards), whereas this deos not work for group creation.

**Comment by axlbonnet** [comment]
There is a difference between groups and users creation :
-  group directory path is linked to the group name, and cannot be configured differently. So if the group directory cannot be created on group creation, there is probably an issue with the group name and the group must not exist.
- for user, the user folder is configurable to be any folder. So an error in the user directory creation can be corrected. Also the folder is created on user activation, not on user registering, so it is to late to remove this new user.

@camarasu Do you agree ?

**Comment by camarasu** [comment]
I agree.
