### ISSUE TITLE
Number column in groups tab

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#122]
what purpose does this column has ?

It's not an ID (when you change the sort column, the numers don't follow their previous group)

Looks useless (at least to display in the groups tab)

**Comment by axlbonnet** [comment]
This number is just the order on the table. There is not much used indeed, it allows to count quickly how many groups there are (but this information could also be displayed elsewhere).

This tab is only accessible to admin. There is not much harm in keeping it.
