### ISSUE TITLE
Query help & documentation

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#123]
What are queries, query explorer & history ?

No hint on the query tabs, nor any help in the documentation tab.

Add a small chapter explaing:
- what it is
- what you can do
- a pointer / link to more extensive doc

**Comment by axlbonnet** [comment]
I can't find it anymore. Have we already removed that ?

**Comment by axlbonnet** [comment]
This has been removed.
