### ISSUE TITLE
Implement CARMIN external storage proposal

### ISSUE THREAD

**Issue by axlbonnet** [virtual-imaging-platform/VIP-portal#199]
See https://github.com/CARMIN-org/CARMIN-API/pull/99

**Comment by camarasu** [comment]
PRs [#211](https://github.com/virtual-imaging-platform/VIP-portal/pull/211) [#212](https://github.com/virtual-imaging-platform/VIP-portal/pull/212), [#214](https://github.com/virtual-imaging-platform/VIP-portal/pull/214)
