### ISSUE TITLE
Create custom error when too many executions

### ISSUE THREAD

**Issue by axlbonnet** [virtual-imaging-platform/VIP-portal#200]
Linked to #84
Currently, all errors are returned with a generic error message with no clue about the real error.

This is especially annoying when this occurs because the user has too many running execution (for instance because one is stuck).

At first, only the case need to be handled but a more ambitious plan about all errors and exceptions should be started.

**Comment by camarasu** [comment]
Too many executions = max authorized reachead

**Comment by axlbonnet** [comment]
Done directly on develop (no PR, wrong git manipulation) with commits https://github.com/virtual-imaging-platform/VIP-portal/commit/ed9b5bc3cb8cab2576fc201152ed1d4825c1091a https://github.com/virtual-imaging-platform/VIP-portal/commit/a48b6eed115d69ef3d87b2ba6b583b7f3cb6c061 and https://github.com/virtual-imaging-platform/VIP-portal/commit/af06f096a35418ca4cfbea0410b39278080d0951

And included in release 1.28.
