### ISSUE TITLE
Update Java version

### ISSUE THREAD

**Issue by camarasu** [virtual-imaging-platform/VIP-portal#219]

**Comment by camarasu** [comment]
Install Java11 (system install) and Tomcat 9 (manual install)
Have a 4 hour downtime for the Tomcat update (but prepare it beforehand)

**Comment by axlbonnet** [comment]
Apache already updated, still java to do.

**Comment by axlbonnet** [comment]
Done in #319

**Comment by axlbonnet** [comment]
Done in #317
