### ISSUE TITLE
VIP support for Boutiques groupes

### ISSUE THREAD

**Issue by camarasu** [virtual-imaging-platform/VIP-portal#236]
Boutiques allows to define groups for inputs : https://github.com/boutiques/boutiques/blob/master/tools/python/boutiques/schema/descriptor.schema.json#L106

This could be helpful in multiple ways, among which :
- custumized GUI in the VIP submit form 
- extra options at application import time, such as specific iteration strategies for the inputs of a group

**Comment by axlbonnet** [comment]
discussed more broadly in #264
