### ISSUE TITLE
Make VIP-Application fields compulsory

### ISSUE THREAD

**Issue by camarasu** [virtual-imaging-platform/VIP-portal#254]
Fields marked with a * should be compulsory, but they aren't

**Comment by camarasu** [comment]
This concerns the Publications module

**Comment by alexcornier** [comment]
- Make the fields for the creation of a new publication mandatory (Title, Type, Typename, Authors, date, VIP Application used): ✔️

**Comment by axlbonnet** [comment]
Done in #353
