### ISSUE TITLE
Support additionnal Boutiques properties/options

### ISSUE THREAD

**Issue by camarasu** [virtual-imaging-platform/VIP-portal#264]
Boutiques schema (https://github.com/boutiques/boutiques/tree/master/schema) supports properties (such as groups and input type properties) that are currently not supported by VIP.

This ticket is about defining which additionnal properties could be supported by VIP and how.

There are roughly three VIP levels impacted :
- (i) when importing a Boutiques descriptor and creating the corresponding workflow file
- (ii) when generating the fill-in form for submitting an execution (currently based on the workflow description generated in the previous step)
- (iii) when generating the moteur inputs out of the previous fill-in form

Since these additionnal properties are not natively supported by Moteur (workflows), the solution will probably consist in relying on the JSON descriptor (and not the workflow file) for step 2 and in 'tricking' Moteur with dummy inputs when needed (as done currently for optional inputs).

A few additionnal considerations (in no particular ordrer) :
- when generating the Moteur workflow, we will have to integrate all possible inputs, regardless of groups and other constraints; all inputs that will not be initialized from the form, will have to have a pre-defined "dummy" value; attention in case these inputs are files, VIP (gasw) will try to download them !
- when generating the fill-in form based on the JSON file, would it be possible to use some of the bosh tools ? the idea is to do a minumum of re-writing and a max of reuse so that if Boutiques/bosh evolves, we can rely on it without having to modify our parsing

**Comment by camarasu** [comment]
Note: relying on the Boutiques descriptor for generating the VIP form implies that Gwendia workflows written "manually" (and with no associated Boutiques descriptor) are no longer supported ..

**Comment by axlbonnet** [comment]
Done in #319
