### ISSUE TITLE
Improve how the gatelab particle numbers are fetched

### ISSUE THREAD

**Issue by axlbonnet** [virtual-imaging-platform/VIP-portal#275]
At the moment, there is an error log `Error fetching simulation particle number` when fetching an gatelab execution information if the execution has just begun or if all the jobs fail.
This should not be an error.

**Comment by axlbonnet** [comment]
There is still an issue when there is no "Somme" table created, an error is displayed on the execution page and makes it difficult to consult the information of the execution.
This happens with Gate execution with a single job if there is an error.

**Comment by camarasu** [comment]
Probably done, to check
