### ISSUE TITLE
List of publications (and applications) in VIP main (non logged-in) page

### ISSUE THREAD

**Issue by camarasu** [virtual-imaging-platform/VIP-portal#328]
The list of publications (and applications) in VIP main (non logged-in) page currently points to static HTML pages. 
It should instead point to an automatic extraction of the VIP database

**Comment by camarasu** [comment]
Suggestion: 
- if we keep GWT, have multiple tabs (simular to Sign in)
- use something else than GWT

**Comment by camarasu** [comment]
Suggestion: keep the same GUI component for publications and change it for applications

**Comment by alexcornier** [comment]
Applications available: ✔️

**Comment by camarasu** [comment]
PRs #349 et #357

**Comment by axlbonnet** [comment]
Corrected in #364 and #365
