### ISSUE TITLE
Boutique schema - 'path-template-stripped-extensions'

### ISSUE THREAD

**Issue by SandeshPatilCreatis** [virtual-imaging-platform/VIP-portal#331]
'path-template-stripped-extensions', A feature of the boutique schema is not functioning properly on VIP. It is to remove the extension of the path template (similar to *baseline* command in bash). It works fine on a local execution, but not with VIP. I have attached a boutique schema of BET (a function of FSL) as an example. 
P.S- It doesn't give any error, but the output is not stripped of it's extension

[fsl-bet-sandesh_github_issue.zip](https://github.com/virtual-imaging-platform/VIP-portal/files/8342315/fsl-bet-sandesh_github_issue.zip)

**Comment by axlbonnet** [comment]
Done in #421
