### ISSUE TITLE
create new "developper" VIP profile

### ISSUE THREAD

**Issue by camarasu** [virtual-imaging-platform/VIP-portal#361]
Define what would be the interesting rights, e. g. importing applications (without being an admin)

**Comment by axlbonnet** [comment]
What rights should a developer have :
- import new applications(access to the "Application Importer" app)
- full access to workflow and jobs logs ("Execution log" panel)
- in a execution page, see the 5 vertical tabs on the left
- in the admin "Application" tool, see and modify its applications (the ones he is the owner). In the "edit application" panel on the top-right, he must see only the classes he has the rights on (through the groups)

A new "Developer" level must be created in the user object.
