### ISSUE TITLE
Improve error message printing time

### ISSUE THREAD

**Issue by camarasu** [virtual-imaging-platform/VIP-portal#363]
Message from Clément : "En ce qui concerne ces messages d'erreurs, peut-être qu'il serait bien de les laisser afficher à l'écran jusqu'à leur fermeture par l'utilisateur. Quand j'ai voulu lancer les 100 jobs, je m'étais trompé dans l'un des 100 noms de fichiers, et puisque que lancer les jobs est assez long, le message d'erreur a eu le temps d’apparaître et de disparaître avant que je m'en aperçoive. J'ai eu de la chance de le voir passer lors du deuxième essai, sans quoi je n'aurais pas su d'où venait l'erreur. "

**Comment by alexcornier** [comment]
Selectable text: ✔️
Increase the time: ✔️

**Comment by axlbonnet** [comment]
In case of error, the error message stays infinitely until the user close it.
