### ISSUE TITLE
Missing "Messages" icon

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#76]
Careful, as I'm new to VIP portal...

The Home page is missing an icon for the "messages" item

![missingicon](https://cloud.githubusercontent.com/assets/12657074/22736857/a62d29f4-ee00-11e6-9b3a-9d3f0effb3ea.jpg)

FF 51.0.1 (64-bit) / Ubuntu 16.10 / amd64
Only blocked site scripts from : google-analytics.com

This does not happen with chromium
Version 56.0.2924.76 Built on Ubuntu , running on Ubuntu 16.10 (64-bit)

**Comment by vincent-legoll** [comment]
Maybe this is a related issue:

There is a hidden (only shown when mouse is over) "messages" item in the title bar, next to the user account button.

![hiddenmessages](https://cloud.githubusercontent.com/assets/12657074/22737650/4a797582-ee04-11e6-8862-2e3e82e58667.jpg)

**Comment by vincent-legoll** [comment]
This does not happen with chromium
Version 56.0.2924.76 Built on Ubuntu , running on Ubuntu 16.10 (64-bit)

**Comment by axlbonnet** [comment]
There have been gwt/smartgwt update since that should have modified the behavior.
