### ISSUE TITLE
UI glitch (partial missing rendering / update) on tab

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#77]
Careful, as I'm new to VIP portal...

The UI is missing some of its UI (not rendered and/or not refreshed): in tab titles & button. I've seen this for different tabs opened from different items from the home tab.

The rendering is correct after a mouseover, though...

![uiglitch](https://cloud.githubusercontent.com/assets/12657074/22737367/1ff9301e-ee03-11e6-825d-dcdcafe7e632.jpg)

The missing part is not always the same (sometimes the button is completely visible whereas the end of the tab is not..., sometimes the button is not visible at all)

FF 51.0.1 (64-bit) / Ubuntu 16.10 / amd64
Only blocked site scripts from : google-analytics.com

**Comment by vincent-legoll** [comment]
This does not happen with chromium
Version 56.0.2924.76 Built on Ubuntu , running on Ubuntu 16.10 (64-bit)

**Comment by axlbonnet** [comment]
There have been gwt/smartgwt update since that should have modified the behavior.
