### ISSUE TITLE
Link to dropbox error does not stop spinner in button

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#83]
Opening the "My Account" page I get an error message:
"Cannot get status of dropbox account".

Pressing the "link dropbox account" button, I got another error, and then the button stays greyed and the wait spinner icon stays spinning forever.

![linktodropboxbtnspinner](https://cloud.githubusercontent.com/assets/12657074/23789040/727f718a-0579-11e7-8382-113adf130747.png)

I'd expect the spinning to stop, and the button to ungrey, and be able to click it again...

**Comment by vincent-legoll** [comment]
Idem with chromium

**Comment by axlbonnet** [comment]
Verify it is not used and delete it if possible.

Similar feature is available through external platform and girder.
