### ISSUE TITLE
Refresh remote files view after operation

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#98]
So that we can see the new content.

I saw this problem:
* after an upload
* after a file delete & go see into the trash

I suspect it is also present for other operations.

I hope this is not "Work-As-Designed", alternatively we could add a checkbox that enable auto-refresh after each operation...

**Comment by axlbonnet** [comment]
This is "Work-As-Designed" as upload and delete operations are asynchonous.
However, the upload operations are tracked in the transfer list on the bottom right and the UI know when the uploads are over. We may use this feature to automatically refresh when an upload is over.

**Comment by axlbonnet** [comment]
Meeting decision :
- try to refresh automatically after upload
- it seems to heavy to refresh automatically while browsing, the idea is to refresh when fetching execution results when the user uses a dedicated link from the execution page ( #274  )

**Comment by axlbonnet** [comment]
Done in #408
