### ISSUE TITLE
Make error popups more useful

### ISSUE THREAD

**Issue by vincent-legoll** [virtual-imaging-platform/VIP-portal#99]
Make them a text box (copy/pasteable) and stop the auto-hide timer when the mouse is over, so that users have time to read them and also can copy the text if needed.

**Comment by vincent-legoll** [comment]
In addition to the above, a way to get back to old error messages would be great (like a console log)

**Comment by axlbonnet** [comment]
It is important to make the text selectable.
Stopping the timer on mouse-over would be great. Then the user can use the close icon to suppress it.
Keeping an history of old errors would be also a plus but needs more time and I don't think this is priority.

**Comment by axlbonnet** [comment]
Meeting decision :
- make the text selectable and stop the closing timer when hovering.

**Comment by axlbonnet** [comment]
Implemented with #363
